// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aggregator/aggregator.proto

package aggregator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AggregatorRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,2,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregatorRequest) Reset()         { *m = AggregatorRequest{} }
func (m *AggregatorRequest) String() string { return proto.CompactTextString(m) }
func (*AggregatorRequest) ProtoMessage()    {}
func (*AggregatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dfac47572f8ed47, []int{0}
}

func (m *AggregatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatorRequest.Unmarshal(m, b)
}
func (m *AggregatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatorRequest.Marshal(b, m, deterministic)
}
func (m *AggregatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatorRequest.Merge(m, src)
}
func (m *AggregatorRequest) XXX_Size() int {
	return xxx_messageInfo_AggregatorRequest.Size(m)
}
func (m *AggregatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatorRequest proto.InternalMessageInfo

func (m *AggregatorRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *AggregatorRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

func (m *AggregatorRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type AggregatorResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AggregatorResponse) Reset()         { *m = AggregatorResponse{} }
func (m *AggregatorResponse) String() string { return proto.CompactTextString(m) }
func (*AggregatorResponse) ProtoMessage()    {}
func (*AggregatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dfac47572f8ed47, []int{1}
}

func (m *AggregatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatorResponse.Unmarshal(m, b)
}
func (m *AggregatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatorResponse.Marshal(b, m, deterministic)
}
func (m *AggregatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatorResponse.Merge(m, src)
}
func (m *AggregatorResponse) XXX_Size() int {
	return xxx_messageInfo_AggregatorResponse.Size(m)
}
func (m *AggregatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatorResponse proto.InternalMessageInfo

func (m *AggregatorResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *AggregatorResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *AggregatorResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AggregatorResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type RediscoverSystemInventoryRequest struct {
	SystemID             string   `protobuf:"bytes,1,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	SystemURL            string   `protobuf:"bytes,2,opt,name=SystemURL,proto3" json:"SystemURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RediscoverSystemInventoryRequest) Reset()         { *m = RediscoverSystemInventoryRequest{} }
func (m *RediscoverSystemInventoryRequest) String() string { return proto.CompactTextString(m) }
func (*RediscoverSystemInventoryRequest) ProtoMessage()    {}
func (*RediscoverSystemInventoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dfac47572f8ed47, []int{2}
}

func (m *RediscoverSystemInventoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RediscoverSystemInventoryRequest.Unmarshal(m, b)
}
func (m *RediscoverSystemInventoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RediscoverSystemInventoryRequest.Marshal(b, m, deterministic)
}
func (m *RediscoverSystemInventoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RediscoverSystemInventoryRequest.Merge(m, src)
}
func (m *RediscoverSystemInventoryRequest) XXX_Size() int {
	return xxx_messageInfo_RediscoverSystemInventoryRequest.Size(m)
}
func (m *RediscoverSystemInventoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RediscoverSystemInventoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RediscoverSystemInventoryRequest proto.InternalMessageInfo

func (m *RediscoverSystemInventoryRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *RediscoverSystemInventoryRequest) GetSystemURL() string {
	if m != nil {
		return m.SystemURL
	}
	return ""
}

type RediscoverSystemInventoryResponse struct {
	TaskURL              string   `protobuf:"bytes,1,opt,name=TaskURL,proto3" json:"TaskURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RediscoverSystemInventoryResponse) Reset()         { *m = RediscoverSystemInventoryResponse{} }
func (m *RediscoverSystemInventoryResponse) String() string { return proto.CompactTextString(m) }
func (*RediscoverSystemInventoryResponse) ProtoMessage()    {}
func (*RediscoverSystemInventoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dfac47572f8ed47, []int{3}
}

func (m *RediscoverSystemInventoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RediscoverSystemInventoryResponse.Unmarshal(m, b)
}
func (m *RediscoverSystemInventoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RediscoverSystemInventoryResponse.Marshal(b, m, deterministic)
}
func (m *RediscoverSystemInventoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RediscoverSystemInventoryResponse.Merge(m, src)
}
func (m *RediscoverSystemInventoryResponse) XXX_Size() int {
	return xxx_messageInfo_RediscoverSystemInventoryResponse.Size(m)
}
func (m *RediscoverSystemInventoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RediscoverSystemInventoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RediscoverSystemInventoryResponse proto.InternalMessageInfo

func (m *RediscoverSystemInventoryResponse) GetTaskURL() string {
	if m != nil {
		return m.TaskURL
	}
	return ""
}

type UpdateSystemStateRequest struct {
	SystemUUID           string   `protobuf:"bytes,1,opt,name=SystemUUID,proto3" json:"SystemUUID,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	SystemURI            string   `protobuf:"bytes,3,opt,name=SystemURI,proto3" json:"SystemURI,omitempty"`
	UpdateKey            string   `protobuf:"bytes,4,opt,name=UpdateKey,proto3" json:"UpdateKey,omitempty"`
	UpdateVal            string   `protobuf:"bytes,5,opt,name=UpdateVal,proto3" json:"UpdateVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSystemStateRequest) Reset()         { *m = UpdateSystemStateRequest{} }
func (m *UpdateSystemStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSystemStateRequest) ProtoMessage()    {}
func (*UpdateSystemStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dfac47572f8ed47, []int{4}
}

func (m *UpdateSystemStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSystemStateRequest.Unmarshal(m, b)
}
func (m *UpdateSystemStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSystemStateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSystemStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSystemStateRequest.Merge(m, src)
}
func (m *UpdateSystemStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSystemStateRequest.Size(m)
}
func (m *UpdateSystemStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSystemStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSystemStateRequest proto.InternalMessageInfo

func (m *UpdateSystemStateRequest) GetSystemUUID() string {
	if m != nil {
		return m.SystemUUID
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetSystemURI() string {
	if m != nil {
		return m.SystemURI
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetUpdateKey() string {
	if m != nil {
		return m.UpdateKey
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetUpdateVal() string {
	if m != nil {
		return m.UpdateVal
	}
	return ""
}

type UpdateSystemStateResponse struct {
	TaskURL              string   `protobuf:"bytes,1,opt,name=TaskURL,proto3" json:"TaskURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSystemStateResponse) Reset()         { *m = UpdateSystemStateResponse{} }
func (m *UpdateSystemStateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSystemStateResponse) ProtoMessage()    {}
func (*UpdateSystemStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dfac47572f8ed47, []int{5}
}

func (m *UpdateSystemStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSystemStateResponse.Unmarshal(m, b)
}
func (m *UpdateSystemStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSystemStateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSystemStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSystemStateResponse.Merge(m, src)
}
func (m *UpdateSystemStateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSystemStateResponse.Size(m)
}
func (m *UpdateSystemStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSystemStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSystemStateResponse proto.InternalMessageInfo

func (m *UpdateSystemStateResponse) GetTaskURL() string {
	if m != nil {
		return m.TaskURL
	}
	return ""
}

func init() {
	proto.RegisterType((*AggregatorRequest)(nil), "AggregatorRequest")
	proto.RegisterType((*AggregatorResponse)(nil), "AggregatorResponse")
	proto.RegisterMapType((map[string]string)(nil), "AggregatorResponse.HeaderEntry")
	proto.RegisterType((*RediscoverSystemInventoryRequest)(nil), "RediscoverSystemInventoryRequest")
	proto.RegisterType((*RediscoverSystemInventoryResponse)(nil), "RediscoverSystemInventoryResponse")
	proto.RegisterType((*UpdateSystemStateRequest)(nil), "UpdateSystemStateRequest")
	proto.RegisterType((*UpdateSystemStateResponse)(nil), "UpdateSystemStateResponse")
}

func init() { proto.RegisterFile("aggregator/aggregator.proto", fileDescriptor_6dfac47572f8ed47) }

var fileDescriptor_6dfac47572f8ed47 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0x12, 0x4d,
	0x14, 0x66, 0xa1, 0xf4, 0x7d, 0x39, 0xb4, 0x89, 0x9d, 0x62, 0x5c, 0x56, 0x53, 0xe9, 0xc4, 0x0b,
	0xae, 0xd6, 0x04, 0x63, 0xaa, 0x4d, 0x4c, 0x84, 0x62, 0xb4, 0xb1, 0xc6, 0x64, 0xb6, 0xf4, 0xca,
	0x9b, 0x69, 0xe7, 0x88, 0x84, 0xed, 0x0e, 0xce, 0xcc, 0x92, 0xec, 0xbf, 0xf2, 0xde, 0x7f, 0xe3,
	0x2f, 0x31, 0xfb, 0xc5, 0x2e, 0x52, 0x44, 0xf4, 0xee, 0x9c, 0xe7, 0x9c, 0x79, 0xce, 0xd7, 0x93,
	0x81, 0x87, 0x7c, 0x3c, 0x56, 0x38, 0xe6, 0x46, 0xaa, 0xa7, 0x85, 0xe9, 0xce, 0x94, 0x34, 0x92,
	0x4e, 0xe1, 0xa0, 0xbf, 0xc0, 0x18, 0x7e, 0x0d, 0x51, 0x1b, 0x42, 0x61, 0xcf, 0x43, 0xad, 0x27,
	0x32, 0xb8, 0x94, 0x53, 0x0c, 0x6c, 0xab, 0x63, 0x75, 0x1b, 0x6c, 0x09, 0x23, 0x1d, 0x68, 0x66,
	0xe9, 0x03, 0x29, 0x22, 0xbb, 0xda, 0xb1, 0xba, 0x7b, 0xac, 0x0c, 0x91, 0x7b, 0x50, 0x1b, 0xb1,
	0x0b, 0xbb, 0x96, 0x3c, 0x8e, 0x4d, 0xfa, 0xc3, 0x02, 0x52, 0xae, 0xa6, 0x67, 0x32, 0xd0, 0x48,
	0x8e, 0x00, 0xb4, 0xe1, 0x26, 0xd4, 0x67, 0x52, 0x60, 0x52, 0xac, 0xce, 0x4a, 0x08, 0x79, 0x02,
	0xfb, 0xa9, 0xf7, 0x01, 0xb5, 0xe6, 0x63, 0x4c, 0x8a, 0x35, 0xd8, 0x32, 0x48, 0x4e, 0x60, 0xf7,
	0x0b, 0x72, 0x81, 0xca, 0xae, 0x75, 0x6a, 0xdd, 0x66, 0xef, 0xb1, 0xbb, 0x5a, 0xca, 0x7d, 0x97,
	0x64, 0xbc, 0x09, 0x8c, 0x8a, 0x58, 0x96, 0x4e, 0x08, 0xec, 0x5c, 0xc7, 0x23, 0xec, 0x24, 0x23,
	0x24, 0xb6, 0xf3, 0x12, 0x9a, 0xa5, 0xd4, 0x78, 0x94, 0x29, 0x46, 0xd9, 0x1e, 0x62, 0x93, 0xb4,
	0xa0, 0x3e, 0xe7, 0x7e, 0x98, 0xf7, 0x92, 0x3a, 0xa7, 0xd5, 0x17, 0x16, 0xfd, 0x04, 0x1d, 0x86,
	0x62, 0xa2, 0x6f, 0xe4, 0x1c, 0x95, 0x17, 0x69, 0x83, 0xb7, 0xe7, 0xc1, 0x1c, 0x03, 0x23, 0x55,
	0x94, 0x2f, 0xd8, 0x81, 0xff, 0xb3, 0xc8, 0x30, 0x23, 0x5d, 0xf8, 0xe4, 0x11, 0x34, 0x52, 0x3b,
	0x5e, 0x5e, 0xca, 0x5e, 0x00, 0xf4, 0x15, 0x1c, 0xff, 0x86, 0x3d, 0x5b, 0xa8, 0x0d, 0xff, 0x5d,
	0x72, 0x3d, 0x8d, 0x09, 0x52, 0xf6, 0xdc, 0xa5, 0xdf, 0x2c, 0xb0, 0x47, 0x33, 0xc1, 0x0d, 0xa6,
	0x6f, 0x3d, 0xc3, 0x0d, 0xe6, 0x5d, 0x1d, 0x01, 0x64, 0x85, 0x46, 0x8b, 0xbe, 0x4a, 0xc8, 0x52,
	0xd7, 0xd5, 0xf5, 0x5d, 0x9f, 0x67, 0x27, 0x2f, 0x80, 0x38, 0x9a, 0x56, 0x7d, 0x8f, 0xe9, 0x9e,
	0x1b, 0xac, 0x00, 0x8a, 0xe8, 0x15, 0xf7, 0xed, 0x7a, 0x39, 0x7a, 0xc5, 0x7d, 0xfa, 0x1c, 0xda,
	0x77, 0x74, 0xbc, 0x69, 0xd2, 0xde, 0xf7, 0x3a, 0x40, 0x21, 0x00, 0x72, 0x02, 0xd0, 0x17, 0xe2,
	0x4c, 0xde, 0xce, 0x42, 0x83, 0x84, 0xb8, 0x2b, 0xa2, 0x77, 0x0e, 0xef, 0xd0, 0x0b, 0xad, 0x90,
	0x01, 0xdc, 0x7f, 0x8b, 0x26, 0x0f, 0x4d, 0x64, 0xe0, 0xa1, 0x9a, 0x4f, 0x6e, 0xb6, 0xe2, 0x38,
	0x85, 0xfd, 0x21, 0xfa, 0x68, 0xf0, 0x2f, 0xea, 0xf7, 0xa0, 0xce, 0x50, 0xa3, 0xd9, 0xe6, 0xcd,
	0x6b, 0x38, 0xf4, 0xd0, 0x0c, 0xf1, 0x33, 0x0f, 0x7d, 0x33, 0x90, 0xd2, 0x7c, 0x54, 0x89, 0xd0,
	0xff, 0x9c, 0x41, 0x40, 0x7b, 0xad, 0xcc, 0xc8, 0xb1, 0xbb, 0x49, 0xe0, 0x0e, 0x75, 0x37, 0xaa,
	0x94, 0x56, 0xc8, 0x05, 0x1c, 0xac, 0x9c, 0x96, 0xb4, 0xdd, 0x75, 0x02, 0x75, 0x1c, 0x77, 0xad,
	0x12, 0x68, 0x85, 0xf4, 0xa1, 0xd5, 0x17, 0xa2, 0x7c, 0x29, 0x19, 0xaa, 0xed, 0x0e, 0x35, 0x84,
	0x07, 0xf1, 0xb1, 0x7d, 0xff, 0x9f, 0x58, 0xfa, 0xd0, 0xfa, 0x45, 0x32, 0xdb, 0x52, 0x5c, 0xef,
	0x26, 0xbf, 0xf3, 0xb3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0x8a, 0x29, 0x84, 0xbc, 0x05,
	0x00, 0x00,
}
